homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone
  name: Hubs
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 172.19.0.0/16
        - 10.0.12.0/24
        - 10.0.11.174/32
      allow_bypass_login: true
    - type: homeassistant

http:
  base_url: http://zwave.constructorfleet.iot
  
frontend:

config:

# Templates
binary_sensor: !include_dir_list binary_sensors

zwave: !include zwave.yaml

mqtt: !include mqtt.yaml
mqtteventstream: !include eventstream.yaml
# mqtt_remoteinstance: !include mqtt_remoteinstance.yaml
